.dependency-cruiser.cjs
package.json
src/convert-virtual-code-owners.spec.ts
src/read-and-convert.spec.ts

Replaces chai expect/ assertion library with functions from node:assert, which ships with the node platform anyway. This way there's less external dependencies and less to maintain/ keep up to date.

refactor(test): replaces chai with node:assert

---

dist/convert-virtual-code-owners.js
src/__fixtures__/CODEOWNERS
src/convert-virtual-code-owners.spec.ts
src/convert-virtual-code-owners.ts

- adds a 'this file was generated' warning at the top of the generated CODE-OWNERS file
Prevents mishaps because you inadvertently edit the generated CODE-OWNERS file.

feat: adds a 'this file was generated' warning at the top of the generated CODE-OWNERS file

---

.c8rc.json
.github/workflows/ci.yml
README.md
dist/convert-virtual-code-owners.js
package.json
src/__fixtures__/CODEOWNERS
src/__mocks__/VIRTUAL-CODEOWNERS.txt
src/convert-virtual-code-owners.spec.ts
src/convert-virtual-code-owners.ts

- Ignore lines staring with `#!` in the input VIRTUAL-CODE-OWNERS.txt
- 🏕️ : combines lint, format, test into one `check` run script
- 🏕️ : removes the `test:cover` run script and makes the `test` run script check coverage (code base is small enough that the overhead doesn't matter)
- 🏕️ : make c8 fail when code coverage is < 100%
- 🏕️ : adds @types/mocha as a devDependency so there's no squigly lines under `describe` and `it` in spec files anymore.
You might want to make comments that shouldn't appear in the CODEOWNERS file, e.g. instructions how to use the VIRTUAL-CODE-OWNERS.txt.
```
#! this is not the CODEOWNERS file - to get that one run
#!   npx virtual-code-owners VIRTUAL-CODE-OWNERS.txt virtual-teams.yml > CODEOWNERS
#! on this.
#!
#! note: lines that start with #! don't appear in …
```

feat: adds ignorable comments to input format

---

.github/CODEOWNERS
.github/VIRTUAL-CODEOWNERS.txt
.github/virtual-teams.yml
README.md
dist/cli.js
dist/convert-virtual-code-owners.js
package.json
src/__fixtures__/CODEOWNERS
src/__mocks__/VIRTUAL-CODEOWNERS.txt
src/cli.ts
src/convert-virtual-code-owners.ts

- replaces positional arguments with options
- adds defaults to the options that should cover 99.9% of the use cases
- removes the posibility to write the output to stdout
- sets process exit to 1 if something went awry (in addition to logging something to stderr)
- dog foods the solution
Easier to use in e.g. lint-staged, and less chance for errors.

feature: adds support for running without arguments BREAKING

---

src/convert-virtual-code-owners.spec.ts
src/convert-virtual-code-owners.ts

- makes the replacement respect word boundaries, so overlapping team names (@team-sub, @team-substring) don't get confused.

fix: makes replacement respect word boundaries

---

dist/convert-virtual-code-owners.js
src/convert-virtual-code-owners.spec.ts
src/convert-virtual-code-owners.ts

- de-duplicates usernames in the resulting CODEOWNERS file
OCD
```
#! VIRTUAL-CODEOWNERS.txt
.github team-a
src/simple-stuff team-a team-b
src/difficult-stuff team-b
```
```yaml
team-a:
- jan
- uitslover
- piet
team-b:
- klaas
- uitslover
- marie
```
```
.github @jan @uitslover @piet
src/simple-stuff @jan @uitslover @piet @klaas @marie
src/difficult-stuff @klaas @uitslover @marie
```
- I am ok with the stuff in [**CONTRIBUTING.md**](https://github.com/sverweij/virtual-code-owners/blob/main/.github/CONTRIBUTING.m …

feat: de-duplicates usernames

---

.github/virtual-teams.yml
dist/convert-virtual-code-owners.js
src/convert-virtual-code-owners.ts
tsconfig.json

- splits off inline function
- reorders function calls in convert-virtual-code-owners top down
- sets moduleResolution in  tsconfig to nodenext
- readability

refactor: splits off inline function

---

.github/CODEOWNERS
.github/VIRTUAL-CODEOWNERS.txt
dist/convert-virtual-code-owners.js
src/convert-virtual-code-owners.spec.ts
src/convert-virtual-code-owners.ts

- now only executes the replace on the usernames part of the string
- leaves spaces between the file name pattern and the usernames in 
This was working correctly before, but only because the file name pattern happens to be at the dead start of the string. This is implicit and can lead to subtle bugs. This refactor makes
it explicit.
The _leaves spaces_ one is for those of us who suffer from OCD.
- I am ok with the stuff in [**CONTRIBUTING.md**](https://github.com/sverweij/virtual-code-owners/blob/main/.github/C …

refactor: makes parsing more robust & leave some of the spaces in place

---

.github/codeql/codeql-config.yml
dist/convert-virtual-code-owners.js
src/__fixtures__/CODEOWNERS
src/convert-virtual-code-owners.spec.ts
src/convert-virtual-code-owners.ts

- sorts the emitted lists of usernames
The lists of CODEOWNERS on the lines can become large. Having the usernames sorted makes visual grepping easier.

feature: sorts usernames

---

dist/convert-virtual-code-owners.js
src/convert-virtual-code-owners.ts

- de-duplicates line parsing
we did this twice; once for replacing the  team names, and once for replacing user names. This is not necessary, and this PR acts on that.

refactor: deduplicates line  parsing

---

dist/convert-virtual-code-owners.js
src/convert-virtual-code-owners.ts

- makes line parsing more explicit, by naming the spaces as well

refactor: makes line parsing more explicit

---

.github/CODEOWNERS
.github/labeler.yml
dist/generate-codeowners.js
dist/generate-labeler-yml.js
src/__fixtures__/CODEOWNERS
src/generate-codeowners.ts
src/generate-labeler-yml.spec.ts
src/generate-labeler-yml.ts

- adds a 'this file is generated' warning comment at the top of .github/labeler.yml
To reduce the number of accidents that will inevitably happen through inadvertently editing the generated .github/labeler.yml

feat(labeler.yml): adds a 'this file is generated' warning comment

---

dist/cli.js
dist/main.js
dist/read-virtual-code-owners.js
src/cli.ts
src/main.spec.ts
src/main.ts
src/read-virtual-code-owners.ts

- moves throwing throwing a formatted parsing error to the spot that reads the virtual  codeowners 
- splits off  the  main functionality  in a function separate from the cli processing
- also puts quotes around the feedback  on  success  (`Wrote  '.github/CODEOWNERS'` instead  of `Wrote  .github/CODEOWNERS`) which  is better  for 
looked a bit better to maintain

refactor: re-organizes main

---

dist/generate-labeler-yml.js
src/generate-labeler-yml.spec.ts
src/generate-labeler-yml.ts

Emits
```yaml
the-configgers:
- "**/*config.js"
```
instead of 
```yaml
the-configgers:
- ;**/*config.js'
```
That's what prettier uses - so this will conflict a bit less with prettier'ing it

fix(generate-labeler-yml): emits " instead of ' to escape * in output

---

README.md
dist/main.js
src/main.spec.ts
src/main.ts

- adds a --dryRun command line option
Useful for validation only scenarios (e.g. on a ci)

feat: adds dry run option

---

dist/generate-codeowners.js
src/generate-codeowners.spec.ts
src/generate-codeowners.ts

- sorts usernames, ignoring case
Make resulting CODEOWNERS files easier to scan/ check.

feat: sorts user names case insensitively

---

src/generate-codeowners.spec.ts
src/generate-labeler-yml.spec.ts
src/parse-virtual-code-owners.spec.ts

- replaces all commonjs looking `__dirname` constructs with the canonical way to do it in ESM
looks cleaner

refactor(test): uses new URL canonically

---

.c8rc.json
.github/workflows/ci.yml
.mocharc.cjs
dist/main.js
package.json
src/generate-codeowners.test.ts
src/generate-labeler-yml.test.ts
src/main.test.ts
src/main.ts
src/parse-virtual-code-owners.test.ts
tools/dependency-cruiser-config/options.yml
tools/dependency-cruiser-config/rules.yml
tsconfig.json

- replaces `mocha` with node's own `node:test` module
Less dependencies = less maintenance

refactor(test): replaces mocha with node:test

---

dist/generate-codeowners.js
src/generate-codeowners.test.ts
src/generate-codeowners.ts

- adds support for inline comments in rule lines in the code that generates the CODEOWNERS file
See #115 

feat(generate): adds support for inline comments in rule lines

---

.github/workflows/ci.yml
package-lock.json
package.json
tsconfig.json

- replaces 'ts-node' with 'tsx'
It's _slightly_ (2x, in this repo) faster and _slightly_ less cumbersome than ts-node to setup and maintain. Also more in line with what is (going to be) used in my other projects.
Faster?
ts-node typically takes 2.5s (ish)
```console
$ yarn test
..................................................
50 passing (2.600 ms)
```
tsx:
```console
$ y test
..................................................
50 passing (1.360 ms)
```
- I am ok with the stuff in …

chore: replaces 'ts-node' with 'tsx'

---

dist/team-map/read.js
dist/team-map/virtual-teams.schema.js
dist/virtual-teams.schema.json
package.json
src/team-map/read.ts
src/team-map/virtual-teams.schema.ts
src/virtual-teams.schema.json
tools/js-json.ts

- loads the teams json schema from a module instead of from a .json
- 🏕️ bumps the schema version to match the (upcoming) version of virtual-code-owners
- code looks easier
- speed wise it doesn't make a noticeable difference (readFileSync + JSON.parse should theoretically be faster as the json parser is simpler, and no module resolution needs to take place - but I guess as the schema is tiny it doesn't matter that much for this use case)
- it _does_ enable for easier bundling (which we're not going to do despite the resulting code running 4-6% faster - the reduced transparency is not worth the hardly noticeable 15ms of 150-250ms (on my slow 2017 machine)).
- The contribution will be subject to …

refactor: load teams json schema from a module

---

.github/labeler.yml
.github/workflows/labeler.yml
README.md
dist/labeler-yml/generate.js
src/labeler-yml/__fixtures__/labeler.yml
src/labeler-yml/generate.test.ts
src/labeler-yml/generate.ts

- changes the --emitLabeler output so it supports the labeler v5 format
actions/labeler [changed their configuration format in a breaking fashion](https://github.com/actions/labeler/issues/712)

feat(labeler.yml): changes --emitLabeler to emit  labeler@v5 format labeler.yml

---

dist/team-map/read.js
package-lock.json
package.json
src/__mocks__/erroneous-virtual-team-is-an-array.yml
src/__mocks__/erroneous-virtual-team-names.yml
src/__mocks__/erroneous-virtual-teams.yml
src/cli.test.ts
src/team-map/read.ts

- replaces the validation of the team map in ajv with a simple hand-rolled one
- removes the 3rd party production dependency 'ajv'
Less dependencies = less worries. Ajv is b.t.w. a great & well maintained package, but for validating the tiny team maps it's overkill. It also makes virtual-code-owners' footprint smaller (ajv is ~120kb minified/ ~35kb compressed - compared to vco itself which has the numbers ~27kb/ ~9kb).
- I am ok with the stuff in [**CONTRIBUTING.md**](https://github.com/sverweij/virtual-code-own …

refactor(team-map): replaces 'ajv' with a hand-rolled validation

---

README.md

- removes gotcha that sections wouldn't work
ain't true anymore 

docs(README): removes gotcha that sections wouldn't work

---

dist/team-map/read.js
dist/virtual-code-owners/read.js
src/team-map/read.ts
src/virtual-code-owners/read.ts

- opens the virtual-teams.yml and virtual-codeowners.txt explicitly as read only
... so there's less chance for accidents - and other process who want to read the files have a better chance.

fix: opens input files explicitly readonly

---

dist/virtual-code-owners/parse.js
src/virtual-code-owners/parse.test.ts
src/virtual-code-owners/parse.ts

- uses a platform independent regex instead of os.EOL for parsing EOL
see comment in committed code for rationale

fix(virtual-code-owners/parse): uses a platform independent regex instead of os.EOL
